# Generated by Django 5.1.4 on 2024-12-31 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuscarPerro',
            new_name='Perro',
        ),
    ]
