# Generated by Django 5.1.4 on 2025-01-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_perro_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='foto',
        ),
    ]
