# Generated by Django 5.1.4 on 2025-01-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_perro_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='direccion',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
