# Generated by Django 5.1.4 on 2025-01-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_perro_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='contacto',
            field=models.EmailField(default=1, max_length=254, verbose_name='@gmail'),
            preserve_default=False,
        ),
    ]
