# Generated by Django 5.1.4 on 2025-01-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_perro_foto_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='foto',
        ),
        migrations.AddField(
            model_name='perro',
            name='imagen',
            field=models.ImageField(default=1, upload_to='perros'),
            preserve_default=False,
        ),
    ]
